name: eureka
version: 0.0.1
author: Name It Later
description: Service discovery framework.
homepage: https://www.github.com/nameitlater/eureka
documentation: https://www.github.com/nameitlater/eureka
environment:
  sdk: '>=1.4.3 <2.0.0'
dependencies:
  args: '>=0.10.0 < 0.11.0'
  intl: '>=0.9.10 < 0.10.0'
  logging: '>=0.9.0 < 0.10.0'
  uuid: '>=0.3.0 < 0.4.0'
  ezetcd:
    git: https://github.com/nameitlater/ezetcd
dev_dependencies:
  unittest: '>=0.11.0 < 0.12.0'
  scheduled_test: '>=0.11.0 <0.12.0'